<a href="https://colab.research.google.com/github/prakhar2000/Twitter-sentiment-analysis/blob/main/Twitter_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [5]:
from google.colab import userdata
import os

os.environ["KAGGLE_USERNAME"] = userdata.get("KAGGLE_USER")
os.environ["KAGGLE_KEY"] = userdata.get("KAGGLE_SECRET")

In [6]:
!kaggle datasets list -s twitter

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                    title                                                   size  lastUpdated                 downloadCount  voteCount  usabilityRating
-----------------------------------------------------  ------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
jp797498e/twitter-entity-sentiment-analysis            Twitter Sentiment Analysis                           2090169  2021-08-09 02:52:11.020000         108103        514                1
goyaladi/twitter-dataset                               Twitter-Dataset                                      1066407  2023-05-16 04:39:29.020000          17992         90                1
crowdflower/twitter-airline-sentiment                  Twitter US Airline Sentiment                         2678605  2019-10-16 00:04:05.163000         145619       1173        0.8235294
thoughtvector/customer-support-on-twitter              Customer Support on Twitter                        176772673  2017-12-03 23:44:27.157000          49078        524        0.9117647
saurabhshahane/twitter-sentiment-dataset               Twitter Sentiment Dataset                            7966522  2021-05-14 18:43:45.307000          24431        128                1
mathurinache/twitter-edge-nodes                        Twitter Edge Nodes                                 358364486  2021-03-08 06:43:04.720000           4610        206                1
hwassner/TwitterFriends                                Twitter Friends                                    183520459  2016-09-02 13:28:00.743000           6131        108        0.7058824
arkhoshghalb/twitter-sentiment-analysis-hatred-speech  Twitter Sentiment Analysis                           1982527  2019-01-06 05:00:19.203000          37376        282       0.64705884
crowdflower/twitter-user-gender-classification         Twitter User Gender Classification                   3163744  2016-11-21 01:48:06.477000          21765        354        0.7058824
yasserh/twitter-tweets-sentiment-dataset               Twitter Tweets Sentiment Dataset                     1289519  2022-04-08 15:39:25.220000          19822        102                1
ayushggarg/all-trumps-twitter-insults-20152021         All Trump's Twitter insults (2015-2021)               594817  2021-01-20 16:51:05.510000           9476        416                1
tariqsays/chatgpt-twitter-dataset                      ChatGPT Twitter Dataset                              8978969  2023-01-24 17:05:17.727000           3936         67                1
umitka/twitter-toxic-tweets                            Twitter Toxic Tweets                                 1291556  2025-12-14 12:42:41.337000           1294         39                1
mksaad/arabic-sentiment-twitter-corpus                 Arabic Sentiment Twitter Corpus                     17700654  2020-07-27 20:57:37.187000          13114         96       0.88235295
markmedhat/twitter                                     twitter                                              2090169  2024-03-15 21:42:01.130000           1649         60        0.4117647
deepcontractor/squid-game-netflix-twitter-data         Squid Game Netflix Twitter Data                     10923670  2022-07-21 11:35:43.280000           4343        103                1
durgeshrao9993/twitter-analysis-dataset-2022           Twitter Sentiment Analysis Dataset                   1291530  2023-07-03 11:38:23.387000           3041         54                1
aadyasingh55/twitter-emotion-classification-dataset    Twitter Emotion Classification Dataset              23423364  2024-10-21 20:47:33.163000           4874         53                1
fifthtribe/how-isis-uses-twitter                       How ISIS Uses Twitter                                2480849  2019-11-14 06:50:54.497000           9719        144        0.7058824
infamouscoder/mental-health-social-media               Depression: Twitter Dataset + Feature Extraction     1150755  2022-08-06 14:26:42.183000          10956         98                1

In [7]:
!kaggle datasets download -d kazanova/sentiment140

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/kazanova/sentiment140
License(s): other
Downloading sentiment140.zip to /content
100% 80.9M/80.9M [00:00<00:00, 180MB/s]

In [8]:
#extracting
from zipfile import ZipFile
dataset ='/content/sentiment140.zip'

with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print('Dataset is extracted')

Dataset is extracted

In [10]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [12]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [14]:
#preprocess data and visaulise
twitter_data= pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding = 'ISO-8859-1')

In [17]:
twitter_data.shape
twitter_data.head()

   0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D
0  0  ...  is upset that he can't update his Facebook by ...
1  0  ...  @Kenichan I dived many times for the ball. Man...
2  0  ...    my whole body feels itchy and like its on fire
3  0  ...  @nationwideclass no, it's not behaving at all....
4  0  ...                      @Kwesidei not the whole crew

[5 rows x 6 columns]

In [18]:
column_names= ['target','id','date','flag','user','text']
twitter_data= pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names=column_names, encoding = 'ISO-8859-1')

In [19]:
twitter_data.shape

(1600000, 6)

In [23]:
twitter_data.isnull().sum()
twitter_data['target'].value_counts()

target
0    800000
1    800000
Name: count, dtype: int64

convert the target from '4' to '1'

In [22]:
twitter_data.replace({'target':{4:1}}, inplace=True)

In [24]:
#stemming: process of reducing a word to its keyword or root word
#eg: actor, actrress, acting = act

port_stem= PorterStemmer()

In [25]:
def stemming(content):
  stemmed_content= re.sub('[^a-zA-Z]',' ',content)
  stemmed_content= stemmed_content.lower()
  stemmed_content= stemmed_content.split()
  stemmed_content= [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]

  return stemmed_content

In [26]:
twitter_data['stemmed_content']= twitter_data['text'].apply(stemming)

In [27]:
twitter_data.head()

   target  ...                                    stemmed_content
0       0  ...  [switchfoot, http, twitpic, com, zl, awww, bum...
1       0  ...  [upset, updat, facebook, text, might, cri, res...
2       0  ...  [kenichan, dive, mani, time, ball, manag, save...
3       0  ...             [whole, bodi, feel, itchi, like, fire]
4       0  ...                 [nationwideclass, behav, mad, see]

[5 rows x 7 columns]

In [28]:
x= twitter_data['stemmed_content'].values
y= twitter_data['target'].values

In [31]:
#splitting data ,
# startify means distribution should be same (else all 0 in train , all 1 in test)
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, stratify=y, random_state=2)

In [32]:
print(x.shape, x_train.shape, x_test.shape)

(1600000,) (1280000,) (320000,)

In [36]:
print(type(x_train))
print(type(x_train[0]))
print(x_train[0])

print(x_train)

<class 'numpy.ndarray'>
<class 'list'>
['watch', 'saw', 'iv', 'drink', 'lil', 'wine']
[list(['watch', 'saw', 'iv', 'drink', 'lil', 'wine'])
 list(['hatermagazin'])
 list(['even', 'though', 'favourit', 'drink', 'think', 'vodka', 'coke', 'wipe', 'mind', 'time', 'think', 'im', 'gonna', 'find', 'new', 'drink'])
 ... list(['eager', 'monday', 'afternoon'])
 list(['hope', 'everyon', 'mother', 'great', 'day', 'wait', 'hear', 'guy', 'store', 'tomorrow'])
 list(['love', 'wake', 'folger', 'bad', 'voic', 'deeper'])]

In [37]:
x_train = [' '.join(words) for words in x_train]
x_test = [' '.join(words) for words in x_test]

In [38]:
#converting text to numerical daat

vectorizer= TfidfVectorizer()

x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [41]:
print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9453092 stored elements and shape (1280000, 461488)>
  Coords	Values
  (0, 436713)	0.27259876264838384
  (0, 354543)	0.3588091611460021
  (0, 185193)	0.5277679060576009
  (0, 109306)	0.3753708587402299
  (0, 235045)	0.41996827700291095
  (0, 443066)	0.4484755317023172
  (1, 160636)	1.0
  (2, 109306)	0.4591176413728317
  (2, 124484)	0.1892155960801415
  (2, 407301)	0.18709338684973031
  (2, 129411)	0.29074192727957143
  (2, 406399)	0.32105459490875526
  (2, 433560)	0.3296595898028565
  (2, 77929)	0.31284080750346344
  (2, 443430)	0.3348599670252845
  (2, 266729)	0.24123230668976975
  (2, 409143)	0.15169282335109835
  (2, 178061)	0.1619010109445149
  (2, 150715)	0.18803850583207948
  (2, 132311)	0.2028971570399794
  (2, 288470)	0.16786949597862733
  (3, 406399)	0.29029991238662284
  (3, 158711)	0.4456939372299574
  (3, 151770)	0.278559647704793
  (3, 56476)	0.5200465453608686
  :	:
  (1279996, 318303)	0.21254698865277744
  (1279996, 434014)	0.27189450523324465
  (1279996, 390130)	0.2206474219107611
  (1279996, 373144)	0.35212500999832036
  (1279996, 238077)	0.5249170684084672
  (1279996, 238078)	0.5606696159563151
  (1279997, 5685)	0.48650358607431304
  (1279997, 273084)	0.4353549002982409
  (1279997, 112591)	0.7574829183045267
  (1279998, 412553)	0.2816582375021589
  (1279998, 93795)	0.21717768937055476
  (1279998, 169461)	0.2659980990397061
  (1279998, 124765)	0.32241752985927996
  (1279998, 435463)	0.2851807874350361
  (1279998, 153281)	0.28378968751027456
  (1279998, 156297)	0.3137096161546449
  (1279998, 162047)	0.34691726958159064
  (1279998, 275288)	0.38703346602729577
  (1279998, 385313)	0.4103285865588191
  (1279999, 242268)	0.19572649660865402
  (1279999, 31410)	0.248792678366695
  (1279999, 435572)	0.31691096877786484
  (1279999, 433612)	0.3607341026233411
  (1279999, 135384)	0.6130934129868719
  (1279999, 96224)	0.5416162421321443

Training the ML model

In [42]:
#logistic regression
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

Model Evaluation

In [43]:
#accuracy score on the training data
x_train_pred= model.predict(x_train)
acc= accuracy_score(y_train, x_train_pred)

In [44]:
print(acc)

0.79871953125

In [46]:
x_test_pred= model.predict(x_test)
acc_test= accuracy_score(y_test, x_test_pred)
print(acc_test)

0.77668125

Saving the model

In [47]:
import pickle
filename= 'trained_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [48]:
loaded_model= pickle.load(open('/content/trained_model.sav', 'rb'))

In [50]:
x_new= x_test[200]
print(y_test[200])
prediction = loaded_model.predict(x_new)
print(prediction)

1
[1]